[project]
name = "local-ai-model-support-in-antigravity-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Avinash", email = "avinash.yadav@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-antigravity>=0.1.18",
    "litert-lm>=0.17.1",
]

[project.scripts]
local-ai-model-support-in-antigravity-sdk = "local_ai_model_support_in_antigravity_sdk:main"
resource-monitor = "local_ai_model_support_in_antigravity_sdk.cli_resource_monitor:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
